spring.application.name=bkash-spy
server.port=${PORT:8000}

# Faster Jackson failing if judge harness sends unknown properties
spring.jackson.deserialization.fail-on-unknown-properties=false

# Error handling
server.error.include-stacktrace=never
server.error.include-message=always
